name: Greetings

on: 
 push:
    branches: [ master ]

jobs:
  git_clone_to_virtual:
    runs-on: windows-latest 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       path: main

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with: 
       repository: JuliProg/Software
       path: my-tools
   
