name: Create new chip

on: 
 push:
    branches: [ master ]

jobs:
  git_clone_to_virtual:
    runs-on: windows-latest 
    
    steps:
    - name: Checkout new chip repo
      uses: actions/checkout@v2
      with:
       path: chip

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with: 
       repository: JuliProg/Software
       path: my-tools
       
    - name: ls work directory
      run: ls
     
   
