name: Create new chip

on: 
 #pull_request:
 push:
    branches: [ master ]

jobs:
  git_clone_to_virtual:
    #runs-on: windows-latest 
    runs-on: ubuntu-latest
    env:
         ACCESS_TOKEN: ${{ secrets.repo_access_token }} 
        
    steps:
    - name: Checkout new chip repo
      uses: actions/checkout@v2
      with:
       path: chip
       token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get JPassist
      uses: actions/checkout@v2
      with: 
       token: ${{ secrets.GITHUB_TOKEN }}
       repository: JuliProg/Software
       path: my-tools
    
    
    
  View_directory:
    runs-on: windows-latest 
      #runs-on: ubuntu-latest
      
    steps:
     - name: view
       working-directory: chip
       id: step_1
      
       #shell: pwsh
       run: |
           ls
           #ls chip
           #cd ..
           ls ..\my-tools
           # Get-Content -Path chip\README.md
           #Get-ComputerInfo
           #ping somee.com
           #curl --help
           #Set-Content -Path CI_CD\file.txt -Value test
           
           New-Item CI_CD\$(Get-Date -Format 'mmHHddMMyyyy').txt
           ls
           
           git config --global user.email "juliprog1110.gmail.com"
           git config --global user.name "JuliProg"
           #git remote -v
           
           git add .
           #git status
           #git add -A
           #git commit -m "Automated report"
           git commit -m 'automated2 add file.txt'
           git push origin master
           
           ls
           
           

      
     
   
