name: Create new chip

on: 
 push:
    branches: [ master ]

jobs:
  git_clone_to_virtual:
    runs-on: windows-latest 
    
    steps:
    - name: Checkout new chip repo
      uses: actions/checkout@v2
      with:
       #path: chip
       token: ${{ secrets.repo_access_token }} 

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with: 
       repository: JuliProg/Software
       path: my-tools
       
    - name: ls work directory
      id: step_1
      run: |
           ls
           #ls chip
           ls my-tools
           # Get-Content -Path chip\README.md
           #Get-ComputerInfo
           #ping somee.com
           #curl --help
           Set-Content -Path file.txt -Value test
           ls
           
           git config --global user.email "juliprog1110.gmail.com"
           git config --global user.name "JuliProg"
           git remote -v
           
           git add file.txt
           git commit -m 'add file.txt'
           #git push
           git status
           

      
     
   
