name: Create new chip

on: 
 #pull_request:
 push:
    branches: [ master ]

jobs:
  git_clone_to_virtual:
    #runs-on: windows-latest 
    runs-on: ubuntu-latest
    env:
         ACCESS_TOKEN: ${{ secrets.repo_access_token }} 
        
    steps:
    - name: Checkout new chip repo
      uses: actions/checkout@v2
      with:
       path: chip
       token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get JPassist
      uses: actions/checkout@v2
      with: 
       token: ${{ secrets.GITHUB_TOKEN }}
       repository: JuliProg/Software
       path: my-tools
    
    - name: view directoris
       #working-directory: chip
       #id: step_1
      
      shell: pwsh
      run: |
           ls -R
           #ls chip
           #cd ..
           #ls my-tools
           # Get-Content -Path chip\README.md
           #Get-ComputerInfo
           #ping somee.com
           #curl --help
           #Set-Content -Path CI_CD\file.txt -Value test
           
          
    - name: delete file from repo
      shell: pwsh  
      run: |   
           #PowerShell command
           Remove-Item  .\chip\CI_CD\*.txt
           
           
    - name: add file to repo
      shell: pwsh  
      run: |   
           #PowerShell command
           New-Item .\chip\CI_CD\$(Get-Date -Format 'mmHHddMMyyyy').txt
           
           
    - name: Push repo-changes to GitHub 
      working-directory: chip
      
      run: |
           git config --global user.email "juliprog1110.gmail.com"
           git config --global user.name "JuliProg"
           #git remote -v
           
           git add .
           #git status
           #git add -A
           #git commit -m "Automated report"
           git commit -m 'automated2 add file.txt'
           git push origin master
    
  View_directory:
    runs-on: windows-latest 
      #runs-on: ubuntu-latest
    needs:  git_clone_to_virtual
    
    steps:
     - name: view on windows
       #working-directory: chip
       #id: step_1
      
       #shell: pwsh
       run: ls
           

      
     
   
