name: Create new chip

on: 
 #pull_request:
 push:
    branches: [ master ]

jobs:
  git_clone_to_virtual:
    runs-on: windows-latest 
    
    steps:
    - name: Checkout new chip repo
      #env:
         #ACCESS_TOKEN: ${{ secrets.repo_access_token }} 
      uses: actions/checkout@v2
      #with:
       #path: chip
       #ref: ${{ secrets.repo_access_token }} 

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with: 
       repository: JuliProg/Software
       path: my-tools
       
    - name: ls work directory
      id: step_1
      run: |
           ls
           #ls chip
           ls my-tools
           # Get-Content -Path chip\README.md
           #Get-ComputerInfo
           #ping somee.com
           #curl --help
           #Set-Content -Path CI_CD\file.txt -Value test
           $filename = Get-Date -Format 'ddMMyyyy' | new-item -path . -name $filename.txt -type file 
           New-Item CI_CD\$(Get-Date -Format 'ddMMyyyy').txt
           ls
           
           git config --global user.email "juliprog1110.gmail.com"
           git config --global user.name "JuliProg"
           #git remote -v
           
           git add .
           #git status
           #git add -A
           #git commit -m "Automated report"
           git commit -m 'automated2 add file.txt'
           git push
           
           ls
           
           

      
     
   
